### ISSUE TITLE
QuantumultX_diy.conf 的 Netflix 分流问题 和 OpenAI无法正常访问APP端（Web没测）

### ISSUE THREAD

**Issue by Hanxiaomo9527** [w37fhy/QuantumultX#56]
1. Netflix 拼写错误为 Netfilx
[policy]
 static=Netfilx, ....
[filter_remote]
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Netflix/Netflix.list, tag=🎬Netflix, force-policy=Netfilx, update-interval=172800, opt-parser=false , enabled=true

2. Netflix 没有增加分流选择为空，可以优化为
static=Netflix, 节点选择, 香港, 台湾, 日本, 韩国, 新加坡, 美国, server-tag-regex=   ...

3. OpenAI 规则可能有点问题，不能正常访问，我这边暂时的解决办法是
[filter_remote]
https://rules-for-qx.sveir.xyz/Rules/Services/OpenAI.list, tag=🤖OpenAI, force-policy=OpenAI, update-interval=172800, opt-parser=false, enabled=true

4. 一些分流规则的不同理解
关于openai，不需要直连，考虑到地区访问等原因，可以优化为
static=OpenAI, 美国, 日本, 韩国, 新加坡, 台湾, img-url=https ........
关于奈飞和漏网之鱼分流如下：
static=Netflix, 节点选择, 香港, 台湾, 日本, 韩国, 新加坡, 美国, server-tag  .....
static=漏网之鱼, PROXY, 自动选择, 香港, 台湾, 日本, 韩国, 新加坡, 美国, 节点选择, DIRECT, img-url=https: .....

**Comment by Baymaxwhite** [comment]
你好，我是白慧文，你发的邮件已收到，我会尽快给你回复！

**Comment by Jay17642121508** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
